version: '3.1'

services:

  baseapp:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    networks:
      - local
    volumes:
      - "./src/app:${WORKING_DIR}"
      - "/tmp:/tmp"
    working_dir: ${WORKING_DIR}
    ports:
      - 80:8000
    expose:
      - "8000"
    env_file:
      - .env

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - "/tmp:/tmp"
    networks:
      - local
    ports:
      - 3306:3306
    expose:
      - "3306"
    env_file:
      - .env

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    expose:
      - "80"
    networks:
      - local
    env_file:
      - .env

networks:
  local: