version: '3.1'

services:

  baseapp:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    networks:
      - local
    tty: true
    volumes:
      - "./src/app:/var/www/go-test-app/src/app"
    working_dir: /var/www/go-test-app/src/app
    ports:
      - 80:8000
    env_file:
      - .env

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: godb
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - "/tmp:/tmp"
    networks:
      - local
    ports:
      - 3306:3306
    expose:
      - "3306"

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_PORT=80
      - PMA_ABSOLUTE_URI=http://localhost
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    restart: always
    expose:
      - "80"
    networks:
      - local

networks:
  local: